project_id = "awmjdbpaknxzhkkuqxsu"

[functions.generate-quote]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false