project_id = "awmjdbpaknxzhkkuqxsu"

[functions.generate-quote]
verify_jwt = false

[functions.analyze-land]
verify_jwt = false

[functions.preprocess-parcel]
verify_jwt = false

[functions.chat]
verify_jwt = false
